### ISSUE TITLE
Trace viewer precision

### ISSUE THREAD

**Issue by danstarns** [rocket-connect/graphql-debugger#7]
* https://github.com/rocket-connect/graphql-debugger/issues/4

## Problem

The trace viewer doesn't accurately display the whole trace, see in the screenshot how we are only plotting spans in MS and not accounting for those spans that are of a lesser value. 

<img width="782" alt="Screenshot 2023-09-03 at 11 09 41" src="https://github.com/rocket-connect/graphql-debugger/assets/35999252/0c7f6636-e90e-4b62-ae02-be2ccc5f36ef">

Due to the fact, we dont account for spans that are of a smaller value than an MS, the width and offset of each trace in the viewer is skewed.

**Comment by Tohaker** [comment]
Trying out a few things, got it displaying the right units at least, depending on how big the `durationNano` value is 
![image](https://github.com/rocket-connect/graphql-debugger/assets/33665681/df4366c8-fe61-4c38-86c3-8d245194bc6b)

Figuring out the width and making the logic reusable will be the next steps

**Comment by Tohaker** [comment]
![image](https://github.com/rocket-connect/graphql-debugger/assets/33665681/e6a771dd-5892-46da-8399-b8fa0e7cd39f)

Played around with some BigInt maths, the existing logic appears overly complicated since it was trying to contextualise everything into `ms` whereas all we needed was a percentage of the total time span. Resolution was also being lost when casting to Number so that's been saved for the last step of the calculations

**Comment by Tohaker** [comment]
Finally, some proper precision in calculating the time;

![image](https://github.com/rocket-connect/graphql-debugger/assets/33665681/a6cbb8ef-1d42-4dde-b528-6cf1f2181846)

I've placed the logic from the `Span` component into the `unix-nano` module so it's all contained in one place, and got some janky BigInt maths holding it all together. I suppose as we're targeting developers machines, browser support isn't top priority and most of this stuff is supported by recent versions of all major browsers so users shouldn't have too hard a time running it
